# Site settings
title: Jan Klosowski
email: contact@janklosowski.com
description: "Human interfaces. Ideas. Noise."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://janklosowski.com" # the base hostname & protocol for your site
parmalink: /:category/:title/
github_username: janklosowski

# Build settings
markdown: kramdown

# Include static files
include:
  - robots.txt

plugins:
  - jekyll-sitemap
